### PR TITLE
Closes issue #2860.

### PR DESCRIPTION
**Pull request by mexvod**
## Related issues
Closes [issue #2860].

### CODE REVIEW

**Comment by mmsmits** [comment]
Thanks for your PR! Really appreciate it. Can you maybe also add a unit test?

**Comment by mexvod** [comment]
> Thanks for your PR! Really appreciate it. Can you maybe also add a unit test?

Ok. I can try. But I can't understand the project structure for tests.

**Comment by mexvod** [comment]
> Thanks for your PR! Really appreciate it. Can you maybe also add a unit test?

I created tests

**Review by mmsmits — APPROVED** [review]

**Comment by mmsmits** [comment]
Thanks so much!

**Pull request merged**
