### PR TITLE
Fix wrong attachment url datatype in PocoSummaryProvider

### LINKED ISSUE #383: Error thrown by validator for a url that need not be resolvable during validation.
Following this profile: https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.2.18/files/2317003

The errors thrown when validating the attached profile against the [Nictiz nl core package.](https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.2.18) 

Profile:
[documentset.zip](https://github.com/user-attachments/files/17455643/documentset.zip)

The new validator v2.4.0 returns:
`Incomplete : Unable to resolve reference to profile 'http://hl7.org/fhir/StructureDefinition/url'
Bundle.entry[1].resource[0].content[0].attachment[0].url[0] `

 See: https://staging.simplifier.net/validator?scope=nictiz.fhir.nl.stu3.zib2017@2.1.5&version=Modern

The legacy validator throws the same error.

### PR DESCRIPTION
**Pull request by mmsmits**
## Description
Changed datatype of attachment.Url from Url to Uri in STU3.

## Related issues
fixes: https://github.com/FirelyTeam/firely-validator-api/issues/383

## Testing
Added new roundtrip test of comparing the SDSummaryProvider vs PocoSummaryProvider for all datatypes.

### CODE REVIEW

**Review by Kasdejong — APPROVED** [review]
Did you do a full run of the validator tests to confirm this does not break our own code? If it does, it may very well break someone else's!

If you have, then consider this an approval :)

**Comment by mmsmits** [comment]
It could break our code, that's why it's a breaking change, but @ewoutkramer and I discussed that we consider this such a minor "breaking bug" that we take the chance.
But you are right. I will run the validation tests before merging, just to be sure.

**Comment by Kasdejong** [comment]
I saw the discussion in FS, so I'm aware that it will indeed be necessary to do here and not in 6.0, I was just wondering if we could get a grasp on how breaking it really is :)

**Comment by mmsmits** [comment]
No changes in the validator unit tests because of this PR. I'm merging this.

**Pull request merged**
