### PR TITLE
Fix/1605 quantity different units

### LINKED ISSUE #1605: Cannot select quantities with different units within a single FHIRPath select
**Describe the bug**
Executing a FHIRPath select statement on an Observation resource containing a quantity in Observation.valueQuantity and Observation.component.valueQuantity with different units results in the following exception:

System.NotSupportedException: Comparing quantities with different units is not yet supported

These values can be selected for example by the following FHIRPath statement: "(Observation.value as Quantity) | (Observation.component.value as Quantity)". This selection is for example done in the SearchParameter "combo-value-quantity" defined on Observation.

The stack trace indicates that some part of the FHIRPath stack is triggering an equal comparison by adding the second value to the result set. 

**To Reproduce**
See unit test "TestSelectDifferentQuantities" in Hl7.FhirPath.R4.Tests.FhirPathTest (Branch: fix/1605-quantity-different-units)

**Expected behavior**
A result set containing both quantities.

**Version used:**
 - FHIR Version: [R4]
 - Version: [2.0.2]

### PR DESCRIPTION
**Pull request by marcovisserFurore**
fixes #1605

### CODE REVIEW

**Review by alexzautke — APPROVED** [review]
Did you intentionally include the OperationsTests.cs in this PR in the common repo? The rest looks good to me.

**Comment by marcovisserFurore** [comment]
I added `OperationsTests.cs` in Common because the bug can be reduced to `4 'g' < 8 '%'`.

**Comment by alexzautke** [comment]
Ah even better!

**Comment by marcovisserFurore** [comment]
Solved in hotfix 2.0.3

**Pull request closed without merging**
